In [1]:
import torch

A = torch.tensor([[1, 2], [3, 4]])
B = torch.tensor([[5, 6], [7, 8]])

# Matrix multiplication using einsum
C = torch.einsum('ij,jk->ik', A, B)

print(C)

tensor([[19, 22],
        [43, 50]])


In [2]:
print(A)
print(B)

tensor([[1, 2],
        [3, 4]])
tensor([[5, 6],
        [7, 8]])


In [3]:
print(torch.matmul(A,B))

tensor([[19, 22],
        [43, 50]])


In [4]:
import torch

# Define input tensors
ij = torch.tensor([[1, 2], [3, 4]])  # Shape: (2, 2)
hwj = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])  # Shape: (2, 2, 2)

# Perform batched matrix multiplication using torch.einsum()
hwi = torch.einsum('ij,hwj->hwi', ij, hwj)

print("First Tensor (ij):")
print(ij)
print("\nSecond Tensor (hwj):")
print(hwj)
print("\nResult of Batched Matrix Multiplication (hwi):")
print(hwi)


First Tensor (ij):
tensor([[1, 2],
        [3, 4]])

Second Tensor (hwj):
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

Result of Batched Matrix Multiplication (hwi):
tensor([[[ 5, 11],
         [11, 25]],

        [[17, 39],
         [23, 53]]])
